### ISSUE TITLE
hard coded values causing image upload to crash.

### ISSUE THREAD

**Issue by hexfusion** [interchange/TableEditor-Plugin-Interchange6#2]
i'm not sure exactly what the best what to handle this is but we can't hard code these as it's impossible to guarantee.  Perhaps we do sth like ('Media')->find({ type => 'image'}); and use logged_in user_id as default here?

app.js line 350

```
author_users_id: "1",
media_types_id: "1",
```

**Comment by racke** [comment]
Right, that is definitely not  a good idea.

**Comment by gregapompe** [comment]
Yes, this was temporary. I'm working on suggested way.

**Comment by gregapompe** [comment]
Fixed https://github.com/interchange/TableEditor-Plugin-Interchange6/commit/b3efb6413adf7abd5bf0868880a5eb4857e3357b
